---
name: benchmark
on:
  push:
    branches:
      - master
jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./rebuild_benchmark.sh
      - uses: peter-evans/create-pull-request@v5